version: '3.8'

services:
#    build:
#        container_name: build
#        build:
#            context: .
#        command: pnpm i
#        volumes:
#            - .:/usr/src/app
#            - /usr/src/app/node_modules
#        restart: unless-stopped
#        networks:
#            - nesjs-network
    client_dev:
        container_name: client_dev
        image: client-dev:1.0.0
        build:
            context: ./packages/client-server/
            target: development
            dockerfile: ./Dockerfile
        command: pnpm run start:debug
        ports:
            - 3002:3002
        networks:
            - nesjs-network
        volumes:
            - ./packages/client-server:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - APP_PORT=3002
            - RESOURCE_SERVICE=http://resource_dev:3001
        restart: unless-stopped

    resource_dev:
        container_name: resource_dev
        image: resource-dev:1.0.0
        build:
            context: ./packages/resource-server/
            target: development
            dockerfile: ./Dockerfile
        command: pnpm run start:debug
        ports:
            - 3001:3001
        networks:
            - nesjs-network
        volumes:
            - ./packages/resource-server/:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - ISSUER=https://acmamarflybot.okta.com/oauth2/aus53f2q22BVsNMk8696
            - APP_PORT=3001
        restart: unless-stopped

networks:
    nesjs-network:
